<a href="https://colab.research.google.com/github/Dcodinginsane/computervision/blob/main/CVT00.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import  tensorflow  as tf



In [ ]:
tensor_zero_d = tf.constant(4)
print(tensor_zero_d)

tf.Tensor(4, shape=(), dtype=int32)


In [ ]:
tensor_one_d = tf.constant([2,0 , -3 , 8 , 90])
print(tensor_one_d)

tf.Tensor([ 2  0 -3  8 90], shape=(5,), dtype=int32)


In [ ]:
tenosr_two_d = tf.constant([[1 ,2 ,0],
                            [3 ,5,1],
                            [1,5,6]])

tenosr_two_d

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 0],
       [3, 5, 1],
       [1, 5, 6]], dtype=int32)>

In [ ]:
tensor_three_d = tf.constant(
    [[[1 ,2,0],
      [3,5,-1]],
    [[10 , 2 ,0],
     [1,0,2]],
     [[2 ,1,9],
      [4 ,-3 ,32]]]
)

tensor_three_d

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  0],
        [ 3,  5, -1]],

       [[10,  2,  0],
        [ 1,  0,  2]],

       [[ 2,  1,  9],
        [ 4, -3, 32]]], dtype=int32)>

In [ ]:
print(tensor_three_d.shape)

(3, 2, 3)


In [ ]:
tensor_four_d = tf.constant(
    [ [[[1 ,2,0],
      [3,5,-1]],
    [[10 , 2 ,0],
     [1,0,2]],
     [[2 ,2,9],
      [4 ,-3 ,32]]],
       [[[1 ,2,0],
      [3,5,-1]],
    [[10 , 2 ,0],
     [1,0,2]],
     [[2 ,1,9],
      [4 ,-3 ,32]]],
       [[[1 ,2,0],
      [3,5,-1]],
    [[10 , 5 ,0],
     [1,0,2]],
     [[2 ,1,9],
      [4 ,-3 ,32]]]]
)

tensor_four_d

<tf.Tensor: shape=(3, 3, 2, 3), dtype=int32, numpy=
array([[[[ 1,  2,  0],
         [ 3,  5, -1]],

        [[10,  2,  0],
         [ 1,  0,  2]],

        [[ 2,  2,  9],
         [ 4, -3, 32]]],


       [[[ 1,  2,  0],
         [ 3,  5, -1]],

        [[10,  2,  0],
         [ 1,  0,  2]],

        [[ 2,  1,  9],
         [ 4, -3, 32]]],


       [[[ 1,  2,  0],
         [ 3,  5, -1]],

        [[10,  5,  0],
         [ 1,  0,  2]],

        [[ 2,  1,  9],
         [ 4, -3, 32]]]], dtype=int32)>

In [ ]:
tensor_one_d = tf.constant([1 ,2,3,4,5] ,dtype=tf.float16)
tensor_one_d

<tf.Tensor: shape=(5,), dtype=float16, numpy=array([1., 2., 3., 4., 5.], dtype=float16)>

In [ ]:
tenosr_one_d = tf.constant([2., 0., -3 , 8 , 90] , dtype = tf.float32)

casted_tensor_one_d = tf.cast(tenosr_one_d , dtype=tf.int16)

print(tensor_one_d)
print(casted_tensor_one_d)

tf.Tensor([1. 2. 3. 4. 5.], shape=(5,), dtype=float16)
tf.Tensor([ 2  0 -3  8 90], shape=(5,), dtype=int16)


In [ ]:
tensor_bool = tf.constant([True , True , False])
print(tensor_bool)

tf.Tensor([ True  True False], shape=(3,), dtype=bool)


In [ ]:
tensor_string = tf.constant(["hello world" , "h1 "])
print(tensor_string)

tf.Tensor([b'hello world' b'h1 '], shape=(2,), dtype=string)


In [ ]:
import numpy as np
np_array = np.array([1 ,2,4])
print(np_array)

converted_tensor = tf.convert_to_tensor(np_array)
print(converted_tensor)

[1 2 4]
tf.Tensor([1 2 4], shape=(3,), dtype=int64)


In [ ]:
eye_tensor = tf.eye(
    num_rows= 3,
    num_columns= None ,
    batch_shape= None ,
    dtype=tf.dtypes.float32,
    name = None

)
print(eye_tensor)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


In [ ]:
eye_tensor = tf.eye(num_rows= 5,
                    num_columns=3,
                    batch_shape=[2 ,],
                    dtype= tf.dtypes.float32)

eye_tensor

<tf.Tensor: shape=(2, 5, 3), dtype=float32, numpy=
array([[[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.],
        [0., 0., 0.],
        [0., 0., 0.]]], dtype=float32)>

In [ ]:
fill_tensor = tf.fill(
    [1 ,3,4] , 5 , name = None

)

print(fill_tensor)

tf.Tensor(
[[[5 5 5 5]
  [5 5 5 5]
  [5 5 5 5]]], shape=(1, 3, 4), dtype=int32)


In [ ]:
one_tensor = tf.ones(
    [5 , 3 ,2]
)
one_tensor

<tf.Tensor: shape=(5, 3, 2), dtype=float32, numpy=
array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]], dtype=float32)>

In [ ]:
ones_like_tensor = tf.ones_like(fill_tensor)
print(ones_like_tensor)

tf.Tensor(
[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]], shape=(1, 3, 4), dtype=int32)


In [ ]:
# shepe of tensor 't' is [2 ,2,3]
t = tf.constant([[1,1,1] , [2,2,2]])
tf.rank(t)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [ ]:
tf.size(t)

<tf.Tensor: shape=(), dtype=int32, numpy=6>

In [ ]:
from tensorflow._api.v2 import random
random_tensor = tf.random.normal(
    [3 ,2] ,
    mean = 100.0,
    stddev = 1.0,
    dtype= tf.dtypes.float32,
    seed = None,
    name = None
)
print(random_tensor)

tf.Tensor(
[[100.48318   99.02794 ]
 [ 98.105194  99.43261 ]
 [ 98.67014   99.54654 ]], shape=(3, 2), dtype=float32)


In [ ]:
random_tensor = tf.random.uniform(
    [5 ,5],
    minval= 0 ,
    maxval= 1000 ,
    dtype = tf.dtypes.int32 ,
    seed = None,
    name = None
)
print(random_tensor)

tf.Tensor(
[[603 738 210 976 500]
 [708 270 990 648 566]
 [ 63 935 709 700 249]
 [848 959 199 979 868]
 [804 143 787 935 235]], shape=(5, 5), dtype=int32)


In [ ]:
tf.random.set_seed(5)
print(tf.random.uniform(shape = [3 ,] , maxval= 5 , dtype=tf.int32 , seed = 10))
print(tf.random.uniform(shape=[3,] , maxval = 5 , dtype=tf.int32 , seed = 10))
print(tf.random.uniform(shape=[3,] , maxval = 5 , dtype=tf.int32 , seed = 10))
print(tf.random.uniform(shape=[3,] , maxval = 5 , dtype=tf.int32 , seed = 10))

tf.Tensor([4 3 1], shape=(3,), dtype=int32)
tf.Tensor([4 3 2], shape=(3,), dtype=int32)
tf.Tensor([1 1 1], shape=(3,), dtype=int32)
tf.Tensor([1 3 3], shape=(3,), dtype=int32)


In [ ]:
tf.random.set_seed(10)
print(tf.random.uniform(shape = [3 ,] , maxval= 5, dtype=tf.int32 , seed = 10))
print(tf.random.uniform(shape=[3,] , maxval = 5 , dtype=tf.int32 , seed = 10))
print(tf.random.uniform(shape=[3,] , maxval = 5 , dtype=tf.int32 , seed = 10))
print(tf.random.uniform(shape=[3,] , maxval = 5 , dtype=tf.int32 , seed = 10))

tf.Tensor([3 4 2], shape=(3,), dtype=int32)
tf.Tensor([3 3 3], shape=(3,), dtype=int32)
tf.Tensor([0 2 3], shape=(3,), dtype=int32)
tf.Tensor([1 3 3], shape=(3,), dtype=int32)


In [ ]:
tensor_indexed = tf.constant([3,6 ,2,4, 66 ,7])
print(tensor_indexed)
print(tensor_indexed)

tf.Tensor([ 3  6  2  4 66  7], shape=(6,), dtype=int32)
tf.Tensor([ 3  6  2  4 66  7], shape=(6,), dtype=int32)


In [ ]:
print(tensor_indexed[0:4])

tf.Tensor([3 6 2 4], shape=(4,), dtype=int32)


In [ ]:
tensor_two_d = tf.constant([[1,2,0],
                           [3,5,-1],
                           [1,5,6],
                           [2,3,8]])

print(tensor_two_d[0:3 , :])

tf.Tensor(
[[ 1  2  0]
 [ 3  5 -1]
 [ 1  5  6]], shape=(3, 3), dtype=int32)


In [ ]:
print(tensor_two_d[...,1])

tf.Tensor([2 5 5 3], shape=(4,), dtype=int32)


In [ ]:
tensor_three_d = tf.constant(
    [
        [[1,2,0],
         [3,5,-1]
         ],
        [[10,2,0],
         [1,0,2]],

        [[5,8,0],
         [2,7,0]],
        [[2,1,9],
         [4,-3,32]]
    ]
)

print(tensor_three_d[0,:,:])

tf.Tensor(
[[ 1  2  0]
 [ 3  5 -1]], shape=(2, 3), dtype=int32)


In [ ]:
x_abs = tf.constant([-2 , 25 , 3.25])
tf.abs(x_abs)

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([ 2.  , 25.  ,  3.25], dtype=float32)>

In [ ]:
t = tf.constant([[1,2,3] ,[5 ,6,7]])
tf.size(t)

<tf.Tensor: shape=(), dtype=int32, numpy=6>

In [ ]:
random_tensor = tf.random.normal(
    [3 ,2] ,
    mean= 0.0
    , stddev= 1.0 ,
    dtype= tf.dtypes.float32,
    seed = None,
    name = None
)

print(random_tensor)

tf.Tensor(
[[-0.8757808   0.3356369 ]
 [-0.35219625 -0.30314562]
 [-0.03882965  0.96529824]], shape=(3, 2), dtype=float32)


In [ ]:
# tf.math.asin
x_abs = tf.constant([-2 , 25 ,3.25])
tf.abs(x_abs)

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([ 2.  , 25.  ,  3.25], dtype=float32)>

In [ ]:
x_abs_complex = tf.constant([-2.25+ 4.75j])
tf.abs(x_abs_complex)

<tf.Tensor: shape=(1,), dtype=float64, numpy=array([5.25594901])>

In [ ]:
tf.sqrt((-2.25)**2 + 4.75**2)

<tf.Tensor: shape=(), dtype=float32, numpy=5.255949>

In [ ]:
x_1 = tf.constant([5 ,3,6,6,4,6], dtype = tf.int32)
x_2 =tf.constant([7,6,2,6,7,11] , dtype = tf.int32)
print(tf.multiply(x_1 , x_2))

tf.Tensor([35 18 12 36 28 66], shape=(6,), dtype=int32)


In [ ]:
print(tf.subtract(x_1 , x_2))

tf.Tensor([-2 -3  4  0 -3 -5], shape=(6,), dtype=int32)


In [ ]:
x_1 = tf.constant([[5,3,6,6,4,6], [5,45,65,5,53,4]], dtype= tf.float32)
x_2 = tf.constant([7], dtype= tf.float32)
x_2_streched = tf.constant([7,7,7,7,7,7],dtype=tf.float32)

In [ ]:
print(tf.math.multiply(x_1 , x_2))

print(tf.math.multiply(x_1,x_2_streched))

tf.Tensor(
[[ 35.  21.  42.  42.  28.  42.]
 [ 35. 315. 455.  35. 371.  28.]], shape=(2, 6), dtype=float32)
tf.Tensor(
[[ 35.  21.  42.  42.  28.  42.]
 [ 35. 315. 455.  35. 371.  28.]], shape=(2, 6), dtype=float32)


In [ ]:
x_argmax = tf.constant([[2 ,20 , 30 , 3 ,6],
                        [3,11,16,1,8],
                        [14,45,23,5,27]])

print(x_argmax.shape)

(3, 5)


In [ ]:
x_argmax = tf.constant([200,120 , 130 , 3 , 6])
print(tf.math.argmax(x_argmax))

tf.Tensor(0, shape=(), dtype=int64)


In [ ]:
print(tf.math.argmin(x_argmax))

tf.Tensor(3, shape=(), dtype=int64)


In [ ]:
x_argmax = tf.constant([[2 ,20 , 30 , 3 ,6],
                        [3,11,16,1,8],
                        [14,45,23,5,27]])

print(x_argmax.shape)
print(tf.math.argmax(x_argmax, 0))

(3, 5)
tf.Tensor([2 2 0 2 2], shape=(5,), dtype=int64)


In [ ]:
print(tf.math.argmax(x_argmax,1))

tf.Tensor([2 2 1], shape=(3,), dtype=int64)


In [ ]:
x = tf.constant([[2,2], [3,3]])
y = tf.constant([[3,0],[1,4]])
tf.pow(x,y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 8,  1],
       [ 3, 81]], dtype=int32)>

In [ ]:
tensor_two_d = tf.constant([[1 ,2,3],
                            [3,5,-1],
                           [1,5,6],
                            [2,3,8]])

print(tensor_two_d)

print(tf.math.reduce_sum(tensor_two_d, axis = None , keepdims=False , name = None))

tf.Tensor(
[[ 1  2  3]
 [ 3  5 -1]
 [ 1  5  6]
 [ 2  3  8]], shape=(4, 3), dtype=int32)
tf.Tensor(38, shape=(), dtype=int32)


In [ ]:
tensor_two_d = tf.constant([[1,-2,0],
                            [3,5,100],
                            [1,5,6],
                            [2,3,8]] , dtype= tf.float16)

print(tensor_two_d.shape)

print(tf.math.reduce_std(tensor_two_d , axis= 0 , keepdims= True , name = None))

(4, 3)
tf.Tensor([[ 0.829  2.861 41.38 ]], shape=(1, 3), dtype=float16)


In [ ]:
tf.math.top_k(tensor_two_d , k =2)

TopKV2(values=<tf.Tensor: shape=(4, 2), dtype=float16, numpy=
array([[  1.,   0.],
       [100.,   5.],
       [  6.,   5.],
       [  8.,   3.]], dtype=float16)>, indices=<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[0, 2],
       [2, 1],
       [2, 1],
       [2, 1]], dtype=int32)>)

### Linear algebra

In [ ]:
x_2 = tf.constant([[1 ,2,0 ,2],
                   [3,5,-1,2],
                   [4,5,6,0]])
x_3 = tf.constant([[1 ,2,0 , 2],
                   [3,5,-1,2]])

print(x_1.shape , x_2.shape , x_3.shape , tf.transpose(x_2).shape)

(2, 6) (3, 4) (2, 4) (4, 3)


In [ ]:
print(x_3@tf.transpose(x_2))

tf.Tensor(
[[ 9 17 14]
 [17 39 31]], shape=(2, 3), dtype=int32)


In [ ]:
tensor_two_d = tf.constant([[1,-2,0],
                           [3,5,100],
                           [1,5,5],
                           [2,3,8]] , dtype = tf.float16)

tensor_out_d = tf.constant([[x , x, x],
                            [x,x,x],
                            [x,x,x],
                            [x,x,x]] , dtype = tf.float16)

#### (m-n <= lower ) and (n-m <= upper)

#m -- rows, n --- columns
tf.linalg.band_part(tensor_two_d, 0 , 0)

ValueError: ignored

In [ ]:
tensor_two_d_m_n = tf.constant([[0,-1,-2],
                                [1,0,-1],
                                [2,1,0],
                                [1,2,1]],  dtype = tf.float16)

tensor_two_d_n_m = tf.constant([[0,1,2],
                                [-1,0,1],
                                [-2,-1,0],
                                [-3,-2,-1]] , dtype = tf.float16)

In [ ]:
tensor_two_d = tf.constant([[1 ,-2 ,0],
                            [3,5,100],
                            [1,5,6]], dtype = tf.float32)

tensor_two_d_inv =tf.linalg.inv(tensor_two_d)

In [ ]:
tensor_two_d@tensor_two_d_inv

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 1.0000000e+00,  7.4505806e-09,  0.0000000e+00],
       [ 1.6391277e-07,  1.0000000e+00,  4.4703484e-08],
       [-5.2154064e-08,  7.4505806e-08,  1.0000000e+00]], dtype=float32)>

In [ ]:
s , u  , v = tf.linalg.svd(tensor_two_d)
print(s)

tf.Tensor([100.3663      5.1059036   1.2371687], shape=(3,), dtype=float32)


In [ ]:
import numpy as np


In [ ]:
A = np.array([[[2,6,5,2],
               [2,-2,2,3],
               [1,5,4,0]],
              [[1,3,1,22],
               [0,2,2,0],
               [1,5,4,1]]])

B = np.array([
    [[2,9,0,3,0],
     [3,6,8,-2,2],
     [1,3,5,0,1],
     [3,0,2,0,5]],
    [[1,0,0,3,0],
     [3,0,4,-2,2],
     [1,0,2,0,0],
     [3,0,1,1,0]]
])

print(A.shape , B.shape)

print("Batch multiplication c = : \n")
print(np.matmul(A , B), "\n")

(2, 3, 4) (2, 4, 5)
Batch multiplication c = : 

[[[33 69 77 -6 27]
  [ 9 12  0 10 13]
  [21 51 60 -7 14]]

 [[77  0 36 19  6]
  [ 8  0 12 -4  4]
  [23  0 29 -6 10]]] 



In [ ]:
# Q = batchsize, s_q, modelsize
# K = batchsize , s_k  , modelsize

In [ ]:
Q = np.random.randn(32 , 64 , 512)
K =  np.random.randn(32 , 128 , 512)

In [ ]:
np.einsum("bqm , bkm -> bqk" , Q , K).shape

(32, 64, 128)

In [ ]:
Q , K

(array([[[-1.72256874e+00, -3.00893464e-01,  5.75229305e-01, ...,
          -6.89693960e-01, -4.12919619e-01, -5.57412824e-03],
         [-4.61150201e-01, -4.33325727e-01,  3.31691282e-01, ...,
           5.95040572e-01,  3.71721752e-01,  1.62111341e-02],
         [-6.72824623e-01,  7.27732594e-01, -1.52904031e+00, ...,
          -7.85454091e-01,  2.66592862e-01,  1.16847427e+00],
         ...,
         [ 1.23142036e+00,  1.28625005e-01, -6.89705809e-01, ...,
          -9.01832679e-01,  5.45021950e-02, -5.86423461e-01],
         [ 1.67816603e+00, -4.60393500e-01,  1.50617424e+00, ...,
          -1.49743933e+00,  3.17085786e-01, -1.56986502e+00],
         [ 1.28137874e+00,  9.65703619e-01, -1.33166338e-01, ...,
           1.35693756e+00, -2.28384867e+00,  1.66258678e-01]],
 
        [[-3.97119205e-01,  9.52114082e-01, -1.66457162e+00, ...,
           2.16031458e+00, -1.17795798e+00,  9.87845549e-01],
         [ 2.75332025e-01, -4.36288926e-01,  5.36531123e-01, ...,
           1.29514689

In [ ]:
A = np.random.randn(2 ,4,4,2) # bcij
B = np.random.randn(2 ,4,4,1) # bcik



In [ ]:
np.einsum("bcik , bcij -> bckj " , B ,A)



array([[[[-1.4366558 , -2.14610808]],

        [[ 0.81692984, -0.4660682 ]],

        [[ 1.84774379, -1.23309168]],

        [[-0.02810752, -2.96152489]]],


       [[[ 0.11222544, -0.90738107]],

        [[ 0.00372097,  1.42130748]],

        [[ 0.43103606,  3.10315985]],

        [[ 1.83563213, -1.05475679]]]])

In [ ]:
np.matmul(np.transpose(B,(0,1,3,2)) ,A)

array([[[[-1.4366558 , -2.14610808]],

        [[ 0.81692984, -0.4660682 ]],

        [[ 1.84774379, -1.23309168]],

        [[-0.02810752, -2.96152489]]],


       [[[ 0.11222544, -0.90738107]],

        [[ 0.00372097,  1.42130748]],

        [[ 0.43103606,  3.10315985]],

        [[ 1.83563213, -1.05475679]]]])

In [ ]:
tensor_three_d = tf.constant([
    [[1,2,0],
     [3,5,-1]],
    [[10,2,0],
     [1,0,2]],
    [[5,8,0],
     [2,7,0]],

    [[2,1,9],
     [4,-3 , 32]]
])

print(tensor_three_d.shape)

print(tf.expand_dims(tensor_three_d , axis = 0).shape)


(4, 2, 3)
(1, 4, 2, 3)


In [ ]:
x = tf.constant([2,3,4,5])

print(x.shape)

print(tf.expand_dims(x , axis=0))

(4,)
tf.Tensor([[2 3 4 5]], shape=(1, 4), dtype=int32)


In [ ]:

x = tf.constant([[[[2,3,4,5]]]])
print(x.shape)

x_squeezed = tf.squeeze(x , axis = 0)

for i in range(2):
  x_squeezed = squeeze(x_squeezed , axis = 0)

  print(x_squeezed)


(1, 1, 1, 4)
[[2 3 4 5]]
[2 3 4 5]
